// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPZlU_9qkqto-XNgksggCQBegRqwCnFhw',
    appId: '1:205358134276:web:bb2c0bd1858b6ce4d23151',
    messagingSenderId: '205358134276',
    projectId: 'admindashboard-e6275',
    authDomain: 'admindashboard-e6275.firebaseapp.com',
    storageBucket: 'admindashboard-e6275.firebasestorage.app',
    measurementId: 'G-JQJV7BSJB9',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjxtiu8gt7LNWmhIBNXUAuk69KqrTS1VE',
    appId: '1:205358134276:ios:c8917378b229350bd23151',
    messagingSenderId: '205358134276',
    projectId: 'admindashboard-e6275',
    storageBucket: 'admindashboard-e6275.firebasestorage.app',
    iosBundleId: 'com.example.admindashboard',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD9hJkDi-aZOUaKyL7jG5LVWBlL_d9dm8',
    appId: '1:205358134276:android:464f85cfec5b0eead23151',
    messagingSenderId: '205358134276',
    projectId: 'admindashboard-e6275',
    storageBucket: 'admindashboard-e6275.firebasestorage.app',
  );

}